[package]
name = "rupdater"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version="1.0.136", features=["derive"]}
confy = "0.4.0"
reqwest = { version = "*", features = ["blocking"]}
